# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 783a5b875c06edbf338991c110dd8765bf01804cca6b3089d31141ca44f7bc62ac2252e487f9498fd52b74e4374ce7b88de0fb516c15deb2377e00eca2c974e0
  basic_auth_name: 'username'
  basic_auth_password:  'password'
  stomp_connection:
    host: 'localhost'
    login: 'admin'
    passcode: 'admin'
  stomp_endpoint: '/queue/some_queue'

test:
  secret_key_base: 8899e4cefc2f51635d5b9aaa6f5344952ebaddae5fd9e8030ae17bf60d279c20aec02ab7044d0d9a518441bcb315e5824e9b483954d219be1ad06b8376daa1a9
  basic_auth_name: 'test_user'
  basic_auth_password:  'password'
  stomp_connection:
    host: 'localhost'
    login: 'username'
    passcode: 'password'
  stomp_endpoint: '/queue/some_queue'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  basic_auth_name: <%= ENV["BASIC_AUTH_NAME"] %>
  basic_auth_password:  <%= ENV["BASIC_AUTH_PASSWORD"] %>
  stomp_connection:
    host: <%= ENV["STOMP_HOST"] %>
    login: <%= ENV["STOMP_USER"] %>
    passcode: <%= ENV["STOMP_PASSWORD"] %>
  stomp_endpoint: <%= ENV["STOMP_ENDPOINT"] %>
